{{- if and .Values.odkCentral.enabled .Values.odkCentral.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "odk-central.backendFullname" . }}
  labels:
    {{- include "odk-central.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "odk-central.backendFullname" . }}
  minReplicas: {{ .Values.odkCentral.autoscaling.minReplicas | default 2 }}
  maxReplicas: {{ .Values.odkCentral.autoscaling.maxReplicas | default 4 }}
  metrics:
    {{- if .Values.odkCentral.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.odkCentral.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.odkCentral.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.odkCentral.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
