{{- if and .Values.odkCentral.enabled .Values.odkCentral.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "odk-central.fullname" . }}
  labels:
    {{- include "odk-central.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "odk-central.selectorLabels" . | nindent 6 }}
  {{- if .Values.odkCentral.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.odkCentral.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.odkCentral.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.odkCentral.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
