{{- if and .Values.odkCentral.enabled .Values.odkCentral.persistence.enabled (not .Values.odkCentral.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "odk-central.pvcName" . }}
  labels:
    {{- include "odk-central.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.odkCentral.persistence.accessModes | nindent 4 }}
  {{- if .Values.odkCentral.persistence.storageClass }}
  storageClassName: {{ .Values.odkCentral.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.odkCentral.persistence.size }}
{{- end }}
