#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=./lib.sh
source "${SCRIPT_DIR}/lib.sh"

ENV_FILE="${1:-${ROOT_DIR}/.env}"
load_env_file "${ENV_FILE}"
require_commands envsubst
require_vars \
  CLOUD_NAME MI_HOSTNAME \
  ENABLE_INGRESS ENABLE_GATEWAY_API INGRESS_CLASS \
  GATEWAY_CREATE GATEWAY_CLASS_NAME GATEWAY_NAME GATEWAY_NAMESPACE \
  GATEWAY_BACKEND_TLS_ENABLED GATEWAY_BACKEND_TLS_HOSTNAME \
  GATEWAY_RATE_LIMIT_ENABLED GATEWAY_RATE_LIMIT_RPS GATEWAY_RATE_LIMIT_BURST \
  CUSTOM_IMAGE_REGISTRY MI_CUSTOM_IMAGE_REPOSITORY MI_IMAGE_TAG MI_IMAGE_PULL_POLICY \
  IMAGE_PULL_SECRET_NAME \
  MI_PORT_OFFSET CURRENCY_SERVICE_URL \
  KEYSTORE_SECRET_NAME KEYSTORE_PASSWORD KEYSTORE_KEY_PASSWORD \
  MI_BUILD_VERSION MI_REPLICAS MI_HPA_ENABLED MI_MIN_REPLICAS MI_MAX_REPLICAS \
  MI_HPA_CPU_PERCENT MI_HPA_MEMORY_PERCENT \
  MI_CPU_REQUEST MI_MEMORY_REQUEST MI_CPU_LIMIT MI_MEMORY_LIMIT MI_JVM_XMS MI_JVM_XMX \
  ICP_RELEASE_NAME ICP_HOSTNAME ICP_BUILD_VERSION \
  ICP_IMAGE_REGISTRY ICP_IMAGE_REPOSITORY ICP_IMAGE_TAG ICP_IMAGE_PULL_POLICY \
  WSO2_IMAGE_PULL_SECRET_NAME \
  ICP_REPLICAS ICP_CPU_REQUEST ICP_MEMORY_REQUEST ICP_CPU_LIMIT ICP_MEMORY_LIMIT \
  ICP_JVM_XMS ICP_JVM_XMX

mkdir -p "${ROOT_DIR}/generated"

envsubst < "${ROOT_DIR}/values/mi-values.yaml.tmpl" > "${ROOT_DIR}/generated/mi-values.yaml"
envsubst < "${ROOT_DIR}/values/icp-values.yaml.tmpl" > "${ROOT_DIR}/generated/icp-values.yaml"

echo "Rendered values files under ${ROOT_DIR}/generated"
