{{- if and .Values.socialRegistry.enabled .Values.socialRegistry.persistence.enabled (not .Values.socialRegistry.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "social-registry.pvcName" . }}
  labels:
    {{- include "social-registry.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.socialRegistry.persistence.accessModes | nindent 4 }}
  {{- if .Values.socialRegistry.persistence.storageClass }}
  storageClassName: {{ .Values.socialRegistry.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.socialRegistry.persistence.size }}
{{- end }}
